# Configuration made available to Spring during initialisation -
# https://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.0.0.M9/multi/multi__spring_cloud_context_application_context_services.html#_the_bootstrap_application_context
spring:
  sleuth:
    enabled: true
    log:
      slf4j:
        enabled: false
    sampler:
      probability: 0.1f
app:
  service:
    name: Stephen
